
spring:
  application:
    name: spring-cloud-provider-demo

  cloud:
    zookeeper:
      connect-string: 10.0.4.79:2182
  boot:
    admin:
      client:
        url: http://localhost:5090

server:
  port: 6091

logging:
  config: classpath:log4j2-spring.xml
  file: logs/sample-boot-application.log
  pattern:
    file: logging.pattern.file=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
debug: true
