server:
  port: 5090
spring:
  application:
    name: zookeeper-example
  cloud:
    config:
      enabled: false
    zookeeper:
      connect-string: 10.0.4.195:2181
      discovery:
        metadata:
#          management.context-path: /
          health.path: /ping
          user.name: user
          user.password: password
        enabled: true
  profiles:
    active:
      - secure

management:
#  server:
#    servlet:
#      context-path: /
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        health: /ping
  endpoint:
    health:
      show-details: ALWAYS
  health:
    zookeeper:
      enabled: true

---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  security:
    user:
      name: "user"
      password: "password"

