server:
  port: 6032

spring:
  application:
    name: spring-cloud-consumer-demo
  cloud:
    zookeeper:
      connect-string: 10.0.4.195:2181
      discovery:
        metadata:
#          management.context-path: /foo
          health.path: /ping
          user.name: user
          user.password: password

  security:
    user:
      name: user
      password: password

management:
#  server:
#    servlet:
#      context-path: /foo
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        health: /ping
  endpoint:
    health:
      show-details: ALWAYS

provider:
  service:
    name: spring-cloud-provider-demo

debug: true

